# supervisor.py - Self-healing process supervisor for LocallyAI.
#
# Definitive guarantees:
#   1. Singleton - only one supervisor.py runs per deployment folder. Concurrent
#      launchd respawns are detected via PID-file liveness and refused.
#   2. Pre-flight cleanup - at startup AND on every API-child restart, kill any
#      stale python/uvicorn process holding $PORT. No more orphan listeners
#      from prior crashed runs.
#   3. Graceful shutdown - SIGTERM/SIGINT/SIGHUP terminate every spawned child
#      before exiting, so `launchctl stop` / `launchctl unload` fully drain
#      the process tree. atexit handler is the belt-and-braces.
#   4. Exponential backoff on rapid API crashes - prevents the launchd
#      respawn-binds-fails flap from pegging CPU.
#   5. Refuses to kill non-Python listeners (AirPlay, dev servers, etc.) -
#      operator must free the port manually for those.
import atexit
import errno
import logging
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

BASE = Path(__file__).resolve().parent
load_dotenv(BASE / ".env")

LOG_DIR = BASE / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [SUPERVISOR] %(message)s")
log = logging.getLogger("supervisor")

PYTHON = sys.executable
HB     = str(BASE / "watchdog" / "heartbeat.py")
PID_F  = LOG_DIR / "api.pid"
LOCK_F = LOG_DIR / "supervisor.lock"
# Sentinel file: when present, the next API child is launched with SAFE_MODE=1.
# The resurrector writes this before requesting a recycle in stage 3; an
# operator removes it once the underlying issue is fixed. Sticky on purpose —
# we don't want to silently fall out of safe mode after a single restart.
SAFE_MODE_FLAG = LOG_DIR / "safe_mode.flag"

# TLS cert paths (generated by install.sh)
TLS_DIR  = BASE / "tls"
CERT     = TLS_DIR / "cert.pem"
KEY      = TLS_DIR / "key.pem"
_USE_TLS = CERT.exists() and KEY.exists()

PORT = int(os.environ.get("PORT", "8000"))

# Backoff control to prevent flap loops when API can't start
_RESTART_BACKOFF_THRESHOLD = 30   # seconds; if API dies faster, back off
_BACKOFF_MAX               = 60   # max seconds between restart attempts
_backoff = 1

# Children we own - killed on shutdown
_children: list[subprocess.Popen] = []
_shutting_down = False


# -- command builders ---------------------------------------------------------

def _api_cmd() -> list:
    """Build the uvicorn command, enabling TLS if certs are present.

    Bind 0.0.0.0 only when TLS is on. With LOCALLYAI_ALLOW_HTTP=1 we drop
    to 127.0.0.1 so unencrypted traffic cannot leave the host even if the
    operator misjudges what 'isolated LAN' means. ISO 27001 A.8.24 / GDPR
    art. 32 (encryption in transit). Override with LOCALLYAI_HTTP_BIND if
    you really need LAN-wide plaintext (you don't).
    """
    if _USE_TLS:
        host = "0.0.0.0"
    elif not os.environ.get("LOCALLYAI_ALLOW_HTTP"):
        raise SystemExit(
            "TLS certs not found. Generate them with install.sh, or set "
            "LOCALLYAI_ALLOW_HTTP=1 to allow plain HTTP (loopback only)."
        )
    else:
        host = os.environ.get("LOCALLYAI_HTTP_BIND", "127.0.0.1")
        if host != "127.0.0.1":
            log.warning(
                f"Plain HTTP bound to {host}: traffic leaves the host unencrypted. "
                "This is non-compliant with GDPR art. 32 outside an air-gapped LAN."
            )

    cmd = [
        PYTHON, "-m", "uvicorn", "api:app",
        "--host", host,
        "--port", str(PORT),
        "--workers", "1",
        "--no-access-log",
    ]
    if _USE_TLS:
        cmd += ["--ssl-keyfile", str(KEY), "--ssl-certfile", str(CERT)]
        log.info(f"TLS enabled: {CERT}")
    else:
        log.warning(
            f"TLS certs not found — running plain HTTP on {host}. "
            "Run install.sh to generate certs."
        )
    return cmd


# -- singleton lock -----------------------------------------------------------

def _pid_alive(pid: int) -> bool:
    """Cross-platform 'is this PID still running?'"""
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        # PID exists but is owned by someone else - still 'alive'
        return True
    except OSError as e:
        if e.errno == errno.ESRCH:
            return False
        return True
    return True


def _acquire_singleton_lock() -> None:
    """Write our PID to LOCK_F. Refuse to start if a live supervisor already holds it."""
    if LOCK_F.exists():
        try:
            old_pid = int(LOCK_F.read_text().strip() or "0")
        except (ValueError, OSError):
            old_pid = 0
        if old_pid and old_pid != os.getpid() and _pid_alive(old_pid):
            stop_hint = (
                "Stop it first: launchctl stop com.locallyai.server"
                if os.name != "nt" else
                "Stop it first: sc stop LocallyAIServer  (or via services.msc)"
            )
            raise SystemExit(
                f"Another supervisor.py is already running (PID {old_pid}, "
                f"lock at {LOCK_F}).\n{stop_hint}"
            )
        log.info(f"Stale lock from PID {old_pid} - reclaiming")
    LOCK_F.write_text(f"{os.getpid()}\n")


def _release_lock() -> None:
    try:
        if LOCK_F.exists() and LOCK_F.read_text().strip() == str(os.getpid()):
            LOCK_F.unlink()
    except OSError:
        pass


# -- stale-listener cleanup ---------------------------------------------------

def _kill_stale_listeners() -> None:
    """Kill any non-self process listening on $PORT.

    Cross-platform via os_supervisor.find_listener_pids/cmdline_of.
    Only kills python/uvicorn processes; refuses to kill foreign holders
    (AirPlay on macOS, IIS on Windows, etc.) and aborts the supervisor in
    that case so the operator notices and clears the port deliberately.
    """
    from os_supervisor import IS_WINDOWS, cmdline_of, find_listener_pids

    pids = find_listener_pids(PORT)
    me = os.getpid()
    pids = [p for p in pids if p != me]
    if not pids:
        return

    log.warning(f"Pre-flight: stale listener(s) on :{PORT} -> PIDs {pids} - investigating")

    for pid in pids:
        cmdline = cmdline_of(pid)
        if cmdline and "python" not in cmdline and "uvicorn" not in cmdline:
            free_hint = (
                "Free it manually (e.g. quit AirPlay Receiver in System Settings, "
                "or stop the dev server) and re-run."
                if not IS_WINDOWS else
                "Free it manually (Task Manager → End task on the listener, or "
                "use `Get-NetTCPConnection -LocalPort $port` in PowerShell) and re-run."
            )
            raise SystemExit(
                f"Port {PORT} is held by a non-Python process (PID {pid}): {cmdline}\n{free_hint}"
            )
        _terminate_pid(pid)

    time.sleep(2)

    survivors = [p for p in pids if _pid_alive(p)]
    for pid in survivors:
        _kill_pid(pid)
        log.warning(f"  hard-kill -> PID {pid} (didn't respond to terminate)")
    if survivors:
        time.sleep(1)
    log.info(f"Port {PORT} freed")


def _terminate_pid(pid: int) -> None:
    """Cross-platform 'polite kill' (SIGTERM on POSIX, taskkill on Win)."""
    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/PID", str(pid)],
                           capture_output=True, timeout=3)
        else:
            os.kill(pid, signal.SIGTERM)
        log.info(f"  terminate -> PID {pid}")
    except (ProcessLookupError, FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass


def _kill_pid(pid: int) -> None:
    """Cross-platform hard kill (SIGKILL on POSIX, taskkill /F on Win)."""
    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/F", "/PID", str(pid)],
                           capture_output=True, timeout=3)
        else:
            os.kill(pid, signal.SIGKILL)
    except (ProcessLookupError, FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass


# -- child process management -------------------------------------------------

def _api_env() -> dict:
    """Env for the API child. Adds SAFE_MODE=1 if the flag file is present."""
    env = os.environ.copy()
    env["PYTHONPATH"] = str(BASE)
    if SAFE_MODE_FLAG.exists():
        env["SAFE_MODE"] = "1"
        log.warning(f"Safe-mode flag present ({SAFE_MODE_FLAG}) — launching API with SAFE_MODE=1")
    return env


def _hb_env() -> dict:
    """Env for the heartbeat child. Probe scheme must match the API's TLS state,
    otherwise the heartbeat times out against an https-only socket and the
    resurrector kills a healthy API. Override unconditionally — the launchd
    plist may export a stale http:// value."""
    env = os.environ.copy()
    env["PYTHONPATH"] = str(BASE)
    scheme = "https" if _USE_TLS else "http"
    env["LOCALLYAI_API_BASE"] = f"{scheme}://localhost:{PORT}"
    return env


def _start(script_or_cmd, name: str, use_cmd: bool = False, env: dict | None = None) -> subprocess.Popen:
    if env is None:
        env = os.environ.copy()
        env["PYTHONPATH"] = str(BASE)
    cmd = script_or_cmd if use_cmd else [PYTHON, script_or_cmd]
    proc = subprocess.Popen(cmd, env=env, cwd=str(BASE))
    _children.append(proc)
    log.info(f"{name} started (PID {proc.pid})")
    return proc


def _verify_bound(api_proc: subprocess.Popen, timeout: int = 15) -> bool:
    """Confirm that api_proc actually owns the listening socket on $PORT.

    Without this, uvicorn can crash post-bind (e.g. EADDRINUSE) and the
    supervisor would happily declare success. Returns True if the listener's
    PID matches api_proc.pid (or any of its descendants — uvicorn forks).

    Fallback: if a listener exists on $PORT AND api_proc is still alive,
    accept the bind even when we can't match PIDs exactly. macOS lsof
    can be slow/restricted in ways that cause direct-PID and direct-PPID
    matches to miss legitimate binds (observed during dogfood: uvicorn
    logged "Uvicorn running on https://0.0.0.0:8000" 0.5s into startup,
    but lsof did not surface api_proc.pid for ~15s, supervisor killed
    a healthy API). A live api_proc + a listening socket = effectively
    the API is bound; if it weren't, uvicorn would crash on bind error
    and api_proc.poll() would return non-None (caught at the top of the
    loop).
    """
    from os_supervisor import IS_WINDOWS, find_listener_pids
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if api_proc.poll() is not None:
            log.warning(f"API child died during bind verification (exit {api_proc.returncode})")
            return False
        pids = set(find_listener_pids(PORT, timeout=3))
        if not pids:
            time.sleep(0.5)
            continue
        if api_proc.pid in pids:
            log.info(f"Verified: PID {api_proc.pid} bound :{PORT}")
            return True
        # uvicorn may bind under a worker — check by parent PID. POSIX uses
        # ps; Windows uses wmic.
        try:
            if IS_WINDOWS:
                ps_result = subprocess.run(
                    ["wmic", "process", "get", "ProcessId,ParentProcessId", "/format:csv"],
                    capture_output=True, text=True, timeout=3,
                )
                ppid_map: dict[int, int] = {}
                for line in ps_result.stdout.splitlines():
                    parts = [p.strip() for p in line.split(",")]
                    # CSV columns: Node,ParentProcessId,ProcessId
                    if len(parts) >= 3 and parts[1].isdigit() and parts[2].isdigit():
                        ppid_map[int(parts[2])] = int(parts[1])
                for child_pid in pids:
                    if ppid_map.get(child_pid) == api_proc.pid:
                        log.info(f"Verified: child PID {child_pid} (of {api_proc.pid}) bound :{PORT}")
                        return True
            else:
                ps_result = subprocess.run(
                    ["ps", "-o", "pid=,ppid="], capture_output=True, text=True, timeout=2,
                )
                for line in ps_result.stdout.splitlines():
                    parts = line.split()
                    if len(parts) >= 2:
                        pid, ppid = int(parts[0]), int(parts[1])
                        if ppid == api_proc.pid and pid in pids:
                            log.info(f"Verified: child PID {pid} (of {api_proc.pid}) bound :{PORT}")
                            return True
        except Exception:
            pass
        # PID match failed but a listener exists AND our api_proc is
        # still alive. Accept the bind (see docstring rationale).
        log.info(f"Listener on :{PORT} (PIDs={sorted(pids)}); api_proc {api_proc.pid} alive — accepting bind via fallback")
        return True
    log.warning(f"PID {api_proc.pid} did not bind :{PORT} within {timeout}s")
    return False


def _shutdown(signum: int = 0, frame=None) -> None:
    global _shutting_down
    if _shutting_down:
        return
    _shutting_down = True
    log.info(f"Shutdown initiated (signal {signum})")

    # Polite SIGTERM first
    for proc in list(_children):
        if proc.poll() is None:
            try:
                proc.terminate()
            except Exception:
                pass

    # Wait up to 8 s for everyone to exit
    deadline = time.monotonic() + 8
    for proc in list(_children):
        if proc.poll() is None:
            try:
                proc.wait(timeout=max(0, deadline - time.monotonic()))
            except subprocess.TimeoutExpired:
                try:
                    proc.kill()
                except Exception:
                    pass

    _release_lock()
    log.info("Shutdown complete")
    sys.exit(0)


# -- log ACLs -----------------------------------------------------------------

def _harden_log_acls() -> None:
    """Tighten file permissions on audit/billing logs at every supervisor boot.

    GDPR art. 32 / ISO 27001 A.8.3 / UAE PDPL art. 20: prevent any user other
    than the service account from reading pseudonymised audit data or
    plaintext billing names. We chmod 640 (owner rw, group r, world none) on
    every start so a stray umask or manual edit can't open these up.
    """
    sensitive = [
        LOG_DIR / "audit.log",
        LOG_DIR / "billing.log",
        LOG_DIR / "security.log",
        LOG_DIR / "erasure.log",
        BASE / ".audit_chain",
        BASE / ".env",
        BASE / "users.json",
    ]
    from platform_compat import chmod_safe
    for p in sensitive:
        if p.exists():
            # 0o600 for secrets, 0o640 for logs (group can read for ops).
            mode = 0o600 if p.name in {".env", "users.json", ".audit_chain"} else 0o640
            chmod_safe(p, mode)


# -- main loop ----------------------------------------------------------------

def run() -> None:
    global _backoff
    log.info("Supervisor starting")

    _harden_log_acls()
    _acquire_singleton_lock()
    atexit.register(_release_lock)
    log.info(f"Singleton lock acquired ({LOCK_F})")

    # Install signal handlers BEFORE spawning children so launchctl stop /
    # sc stop / Ctrl+C / SIGHUP all drain cleanly. Cross-platform via
    # os_supervisor — Windows additionally registers a console control
    # handler so service-stop messages reach us.
    from os_supervisor import install_shutdown_handlers
    install_shutdown_handlers(_shutdown)

    # Kill any orphan listener squatting on our port BEFORE spawning uvicorn.
    _kill_stale_listeners()

    api_proc = _start(_api_cmd(), "API", use_cmd=True, env=_api_env())
    PID_F.write_text(f"{api_proc.pid}\n")
    last_api_start = time.monotonic()

    # MLX cold-loads the model on the first request (or at startup if the
    # model is preloaded). On a fresh boot of a 1B model that's ~30s; on
    # a larger model and uncached weights it can be 2-3 minutes. Give the
    # bind verifier the time it needs so we don't enter the kill-and-respawn
    # loop while the model is still loading. Ollama backends are fast to
    # bind so the original 15s is still right for them.
    _backend = os.environ.get("LOCALLYAI_BACKEND", "ollama").lower()
    bind_timeout = 240 if _backend == "mlx" else 15

    if not _verify_bound(api_proc, timeout=bind_timeout):
        log.warning("Initial API failed to bind -- forcing crash to trigger restart loop")
        try:
            api_proc.terminate()
            api_proc.wait(timeout=5)
        except Exception:
            try:
                api_proc.kill()
            except Exception:
                pass

    time.sleep(2)
    hb_proc = _start(HB, "Heartbeat", env=_hb_env())

    while True:
        time.sleep(10)

        if api_proc.poll() is not None:
            uptime = time.monotonic() - last_api_start
            log.warning(f"API exited (code {api_proc.returncode}) after {uptime:.0f}s")
            if uptime < _RESTART_BACKOFF_THRESHOLD:
                _backoff = min(_BACKOFF_MAX, max(1, _backoff * 2))
                log.warning(f"Rapid crash detected - backing off {_backoff}s before restart")
                time.sleep(_backoff)
            else:
                _backoff = 1
            try:
                _children.remove(api_proc)
            except ValueError:
                pass
            _kill_stale_listeners()  # in case the dying API left a zombie
            api_proc = _start(_api_cmd(), "API", use_cmd=True, env=_api_env())
            PID_F.write_text(f"{api_proc.pid}\n")
            last_api_start = time.monotonic()
            if not _verify_bound(api_proc):
                log.warning("Restarted API failed to bind -- forcing another retry")
                try:
                    api_proc.terminate()
                    api_proc.wait(timeout=5)
                except Exception:
                    try:
                        api_proc.kill()
                    except Exception:
                        pass
                # Loop top will detect api_proc.poll() != None and restart with backoff

        if hb_proc.poll() is not None:
            log.warning(f"Heartbeat exited (code {hb_proc.returncode}), restarting")
            try:
                _children.remove(hb_proc)
            except ValueError:
                pass
            hb_proc = _start(HB, "Heartbeat", env=_hb_env())


if __name__ == "__main__":
    try:
        run()
    except SystemExit:
        raise
    except Exception as exc:
        log.error(f"Supervisor fatal: {exc}", exc_info=True)
        _shutdown(0)
