// LocallyAI kill-switch Cloudflare Worker (KV-backed)
// ----------------------------------------------------
// Server-mediated TOTP auth for the kill-switch JSON. The JSON itself
// lives in this Worker's Cloudflare KV namespace — no GitHub repo,
// no PAT, no second GitHub account needed.
//
// Threat-model improvement over the previous GitHub-backed design:
//   - Zero GitHub surface area for the kill switch. Compromising the
//     LocallyAI org account doesn't reach the kill switch at all.
//   - One credential boundary instead of two: the operator's TOTP
//     code (phone) + Cloudflare account (separate from GitHub).
//   - Worker write goes to KV with the Worker's own runtime perms;
//     no token to leak.
//
// API:
//   GET  /                  → returns current status JSON (no auth, public)
//   POST /                  → { action: {...}, auth: "<6-digit OR recovery>" }
//                             validates auth, mutates KV.
//
// Required secrets (set via `wrangler secret put`):
//   TOTP_SECRET_BASE32       generated by scripts/kill_switch_totp_setup.sh
//   RECOVERY_CODES_HASHED    JSON array of sha256(code) strings
//
// Required KV binding (set via wrangler.toml):
//   KILLSWITCH               the namespace holding the single key "status"

interface Env {
  TOTP_SECRET_BASE32:    string;
  RECOVERY_CODES_HASHED: string;
  KILLSWITCH:            KVNamespace;
}

const KV_KEY = "status";

// ── RFC 4648 base32 decode ───────────────────────────────────────────────────
function base32Decode(input: string): Uint8Array {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
  const cleaned = input.replace(/[\s=]/g, "").toUpperCase();
  let bits = "";
  for (const c of cleaned) {
    const v = alphabet.indexOf(c);
    if (v < 0) throw new Error(`Invalid base32 char: ${c}`);
    bits += v.toString(2).padStart(5, "0");
  }
  const bytes = new Uint8Array(Math.floor(bits.length / 8));
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(bits.slice(i * 8, i * 8 + 8), 2);
  }
  return bytes;
}

// ── RFC 6238 TOTP (HMAC-SHA1, 30 s step, 6 digits) ──────────────────────────
async function totp(secret: Uint8Array, t: number): Promise<string> {
  const buf = new ArrayBuffer(8);
  new DataView(buf).setUint32(4, t, false);
  const key = await crypto.subtle.importKey(
    "raw", secret as BufferSource, { name: "HMAC", hash: "SHA-1" }, false, ["sign"],
  );
  const sigBuf = await crypto.subtle.sign("HMAC", key, buf);
  const sig = new Uint8Array(sigBuf);
  const offset = sig[sig.length - 1] & 0x0f;
  const code =
    ((sig[offset] & 0x7f) << 24) |
    ((sig[offset + 1] & 0xff) << 16) |
    ((sig[offset + 2] & 0xff) << 8) |
    (sig[offset + 3] & 0xff);
  return (code % 1_000_000).toString().padStart(6, "0");
}

async function verifyTotp(secretBase32: string, supplied: string): Promise<boolean> {
  if (!/^\d{6}$/.test(supplied)) return false;
  const secret = base32Decode(secretBase32);
  const t = Math.floor(Date.now() / 30_000);
  for (const offset of [-1, 0, 1] as const) {
    const expected = await totp(secret, t + offset);
    if (timingSafeEqual(expected, supplied)) return true;
  }
  return false;
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let r = 0;
  for (let i = 0; i < a.length; i++) {
    r |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return r === 0;
}

async function sha256Hex(s: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function verifyRecovery(supplied: string, env: Env): Promise<boolean> {
  if (!env.RECOVERY_CODES_HASHED) return false;
  let hashes: string[] = [];
  try { hashes = JSON.parse(env.RECOVERY_CODES_HASHED); } catch { return false; }
  if (hashes.length === 0) return false;
  const got = await sha256Hex(supplied.trim().toLowerCase());
  return hashes.some((h) => timingSafeEqual(h, got));
}

// ── Action types + payload shape ─────────────────────────────────────────────
type Action =
  | { op: "stop"; message?: string }
  | { op: "resume" }
  | { op: "blocklist"; tag: string }
  | { op: "unblocklist"; tag: string }
  | { op: "require-version"; version: string };

interface KillSwitchPayload {
  version: 1;
  kill_switch_active: boolean;
  blocklisted_tags: string[];
  min_required_version: string;
  rollback_to_version: string | null;
  message: string;
  updated_at: string;
}

const DEFAULT_PAYLOAD: KillSwitchPayload = {
  version: 1,
  kill_switch_active: false,
  blocklisted_tags: [],
  min_required_version: "0.0.0",
  rollback_to_version: null,
  message: "",
  updated_at: "1970-01-01T00:00:00Z",
};

// ── KV helpers ───────────────────────────────────────────────────────────────
async function readPayload(env: Env): Promise<KillSwitchPayload> {
  const raw = await env.KILLSWITCH.get(KV_KEY);
  if (!raw) return { ...DEFAULT_PAYLOAD };
  try {
    const parsed = JSON.parse(raw) as KillSwitchPayload;
    return { ...DEFAULT_PAYLOAD, ...parsed };  // schema-tolerate older payloads
  } catch {
    return { ...DEFAULT_PAYLOAD };
  }
}

async function writePayload(env: Env, p: KillSwitchPayload): Promise<void> {
  p.updated_at = new Date().toISOString();
  await env.KILLSWITCH.put(KV_KEY, JSON.stringify(p, null, 2));
}

function applyAction(p: KillSwitchPayload, a: Action): KillSwitchPayload {
  switch (a.op) {
    case "stop":
      return { ...p, kill_switch_active: true, message: a.message || "updates paused" };
    case "resume":
      return { ...p, kill_switch_active: false, message: "" };
    case "blocklist": {
      const set = new Set(p.blocklisted_tags || []);
      set.add(a.tag);
      return { ...p, blocklisted_tags: [...set].sort() };
    }
    case "unblocklist":
      return { ...p, blocklisted_tags: (p.blocklisted_tags || []).filter((t) => t !== a.tag) };
    case "require-version":
      return { ...p, min_required_version: a.version };
  }
}

function badRequest(msg: string, status = 400): Response {
  return new Response(JSON.stringify({ ok: false, error: msg }), { status, headers: { "Content-Type": "application/json" } });
}

// ── Worker entrypoint ────────────────────────────────────────────────────────
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // GET = read-only public status (this is what office Macs poll).
    if (request.method === "GET") {
      const payload = await readPayload(env);
      return new Response(JSON.stringify(payload, null, 2), {
        status: 200,
        headers: {
          "Content-Type":  "application/json",
          // 60 s aligns with the office-Mac kill_switch.py cache TTL.
          // Operators flipping the switch see propagation in ≤60 s.
          "Cache-Control": "public, max-age=60",
          "Access-Control-Allow-Origin": "*",  // public read; no creds
        },
      });
    }
    if (request.method !== "POST") {
      return new Response("method not allowed", { status: 405, headers: { "Allow": "GET, POST" } });
    }

    let body: { action?: Action; auth?: string };
    try {
      body = await request.json();
    } catch { return badRequest("invalid JSON body"); }

    if (!body.action || !body.auth) return badRequest("missing 'action' or 'auth'");
    const op = (body.action as { op: string }).op;
    if (!["stop", "resume", "blocklist", "unblocklist", "require-version"].includes(op)) {
      return badRequest(`unknown action op: ${op}`);
    }
    if (op === "require-version" && !/^\d+\.\d+\.\d+$/.test((body.action as { version: string }).version || "")) {
      return badRequest("require-version expects semver x.y.z");
    }
    if ((op === "blocklist" || op === "unblocklist") &&
        !/^v?\d+\.\d+\.\d+(-[a-z0-9.-]+)?$/i.test((body.action as { tag: string }).tag || "")) {
      // Accept v1.2.0, v1.2.0-stable, v1.2.0-rc.1, v1.2.0-fake-test, etc.
      // (alphanumerics + dots + hyphens after the first hyphen).
      return badRequest("blocklist/unblocklist expects a tag like v1.2.0-stable");
    }

    // ── Auth ────────────────────────────────────────────────────────────────
    const totpOk = await verifyTotp(env.TOTP_SECRET_BASE32, body.auth);
    const recoveryOk = !totpOk && await verifyRecovery(body.auth, env);
    if (!totpOk && !recoveryOk) return badRequest("invalid TOTP / recovery code", 401);

    // ── Mutate KV ───────────────────────────────────────────────────────────
    const before = await readPayload(env);
    const after = applyAction(before, body.action);
    await writePayload(env, after);

    return new Response(JSON.stringify({ ok: true, payload: after, used_recovery: recoveryOk }, null, 2), {
      status: 200, headers: { "Content-Type": "application/json" },
    });
  },
};
