/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SystemRouteImport } from './routes/system'
import { Route as QueryRouteImport } from './routes/query'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/conflicts': typeof ConflictsRoute
  '/documents': typeof DocumentsRoute
  '/downloads': typeof DownloadsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/query': typeof QueryRoute
  '/system': typeof SystemRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/conflicts': typeof ConflictsRoute
  '/documents': typeof DocumentsRoute
  '/downloads': typeof DownloadsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/query': typeof QueryRoute
  '/system': typeof SystemRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/conflicts': typeof ConflictsRoute
  '/documents': typeof DocumentsRoute
  '/downloads': typeof DownloadsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/query': typeof QueryRoute
  '/system': typeof SystemRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/compare'
    | '/compliance'
    | '/conflicts'
    | '/documents'
    | '/downloads'
    | '/mcp'
    | '/models'
    | '/plugins'
    | '/query'
    | '/system'
    | '/updates'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/compare'
    | '/compliance'
    | '/conflicts'
    | '/documents'
    | '/downloads'
    | '/mcp'
    | '/models'
    | '/plugins'
    | '/query'
    | '/system'
    | '/updates'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/compare'
    | '/compliance'
    | '/conflicts'
    | '/documents'
    | '/downloads'
    | '/mcp'
    | '/models'
    | '/plugins'
    | '/query'
    | '/system'
    | '/updates'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CompareRoute: typeof CompareRoute
  ComplianceRoute: typeof ComplianceRoute
  ConflictsRoute: typeof ConflictsRoute
  DocumentsRoute: typeof DocumentsRoute
  DownloadsRoute: typeof DownloadsRoute
  McpRoute: typeof McpRoute
  ModelsRoute: typeof ModelsRoute
  PluginsRoute: typeof PluginsRoute
  QueryRoute: typeof QueryRoute
  SystemRoute: typeof SystemRoute
  UpdatesRoute: typeof UpdatesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CompareRoute: CompareRoute,
  ComplianceRoute: ComplianceRoute,
  ConflictsRoute: ConflictsRoute,
  DocumentsRoute: DocumentsRoute,
  DownloadsRoute: DownloadsRoute,
  McpRoute: McpRoute,
  ModelsRoute: ModelsRoute,
  PluginsRoute: PluginsRoute,
  QueryRoute: QueryRoute,
  SystemRoute: SystemRoute,
  UpdatesRoute: UpdatesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
